### ISSUE TITLE
[Bug] Text formatting in the RU wiki-graph

### ISSUE THREAD

**Issue by SlumberyDude** [blinpete/wiki-graph#1]
**Issue with text formatting in the RU wiki-graph**
It seems that the text of some articles isn't properly formatted, as we can see on the screenshot

![image](https://user-images.githubusercontent.com/13641456/190892967-6f9d5ca3-05a9-4db8-a7bb-36bc9a9ce75f.png)

**Comment by blinpete** [comment]
@SleepyDude, thnx for the report!

just fixed,
the website is up to date.
