### ISSUE TITLE
[Bug] Doesn't work in Firefox browser.

### ISSUE THREAD

**Issue by FoxSquared** [blinpete/wiki-graph#3]
When I make requests I get this

![Безымянный](https://user-images.githubusercontent.com/41552528/190903444-4c7789be-b949-4f4a-a6c9-8823a12e9f6f.png)

Nothing happened! Page didn't even tell me if something wrong.

I used Firefox ver. 104.0.2.

**Comment by blinpete** [comment]
fixed in the commit 6ed57df704908305029e516358212714192d614c

@FoxSquared,
thanks for your report!
