### ISSUE TITLE
Readme outdated

### ISSUE THREAD

**Issue by Ein0815er** [blinpete/wiki-graph#5]
**Describe the bug**
Hey, the Link in the README to batou's [wikipedia-explorer](https://batou.xyz/explorer/) has a redirect to something completely unrelated...

(Is this ok to report something like that in this way?)

**Comment by blinpete** [comment]
Hey @Ein0815er!

Ohh seems like `batou` are now focused on Fermat and closed their Wikipedia explorer.

I've just updated the link in Readme. Unfortunately, the only thing left from the Explorer is their launch page on ProductHunt.

thanks for your report 👍
